config/routes.rb
Rails.application.routes.draw do

  root 'vibes#index'

  resources :posts
  resources :vibes

end

app/models/post.rb
class Post < ActiveRecord::Base

	def getSrc
		if self.uid
			source="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/"
			source += self.uid
			source += "&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false&amp;visual=true"
		end	
	end

end

app/models/vibe.rb
class Vibe < ActiveRecord::Base

	def getSrc
		if self.vibeType == "2"
			source ="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/"
			source += self.uid
			source += "&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false&amp;visual=true"
		else self.vibeType == "3"
			source ="https://www.youtube.com/embed/"
			source += self.uid if self.uid
		end	
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
  	@post = Post.order('created_at DESC') # .page(params[:page])
  end

  def edit
  	@post = Post.find(params[:id])
  end

  def show
  	@post = Post.find(params[:id])
  end

  def new
  	@post = Post.new
  end

  def create
    @post = Post.new(post_params)


    start= 'content="soundcloud://sounds:'
    i = open(@post.url).read.index(start)

    @post.uid = open(@post.url).read[i+29..i+37] 

    respond_to do |format|
      if @post.save
        format.html { redirect_to root_path, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
	end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :url, :uid)
    end
end



# # in ruby we can use open-uri

# # require 'open-uri'
# # open("http://soundcloud.com") do |f|
# # 	puts f.base_uri
# # 	puts f.status
# # end

# page_source.index('content="soundcloud://sounds:')

# # page_source[2799:]

# start = 'content="soundcloud://sounds:'
# end = '"><meta property='
# s = page_source.index(start)

# # get the first index of end in the range starting at the index of s and to the end
# e = page_source.index(end, s)

# ourLine = page_source[s:e]

# # 'content="soundcloud://sounds:198813741'


#  tracknum = ourline[ourline.index("sounds:")+7:]

app/controllers/vibes_controller.rb
class VibesController < ApplicationController
  def index
  	@vibe = Vibe.order('created_at DESC') # .page(params[:page])
  end

  def edit
  	@vibe = Vibe.find(params[:id])
  end

  def show
  	@vibe = Vibe.find(params[:id])
  end

  def new
  	@vibe = Vibe.new
  end

  def create
    @vibe = Vibe.new(vibe_params)

    if @vibe.vibeType == "2"
	    start= 'content="soundcloud://sounds:'
	    i = open(@vibe.url).read.index(start)
	    @vibe.uid = open(@vibe.url).read[i+29..i+37] 
  	elsif @vibe.vibeType == "1"
  		@vibe.uid = @vibe.url
  	elsif @vibe.vibeType == "3"
      start = 'watch'
      i = @vibe.url.index(start)
      pp = @vibe.url[i, i+1]
  		@vibe.uid = pp[8,100]
	end
		

    respond_to do |format|
      if @vibe.save
        format.html { redirect_to root_path, notice: 'vibe was successfully created.' }
        format.json { render :show, status: :created, location: @vibe }
      else
        format.html { render :new }
        format.json { render json: @vibe.errors, status: :unprocessable_entity }
      end
	end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vibe
      @vibe = vibe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vibe_params
      params.require(:vibe).permit(:vibeType, :title, :body, :url, :approved)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/vibes_helper.rb
module VibesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<div class="mainForm">
	<%= form_for(@post) do |f| %>

		<%= f.text_field :url %>

		<%= f.submit "submit" %>

	<% end %>
</div>

app/views/posts/edit.html.erb
<%= render 'form' %>

app/views/posts/index.html.erb
<div class="mainForm">


<h1 id="header-button"><%= link_to "submit", new_post_path %> </h1>

	<div id="container" data-masonry-options='{ "itemSelector": ".item", "columnWidth": 320 }'>
	
		<% @post.each do |post| %>
			<div class="item"> 
				<iframe id="what" width="100%" height="150" scrolling="no" frameborder="no" src="<%= post.getSrc.to_s %>" ></iframe> 
			</div>
		<% end %>
		<div class="item"><img src="/assets/rolf.jpg"></div>
		<div class="item"><img src="/assets/braislakeitaly.jpg"></div>
		<div class="item"><img src="/assets/chilevolcano.jpg"></div>
		<div class="item"><img src="/assets/coolhaus.jpg"></div>
		<div class="item"><iframe src="https://www.youtube.com/embed/lCDKk2s0pQM" frameborder="0" allowfullscreen></iframe></div>
		<div class="item"><img src="/assets/fireflies.jpg"></div>
		<div class="item"><img src="/assets/nice.jpg"></div>
		<div class="item"><iframe scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/202830372&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false&amp;visual=true"></iframe></div>
		<div class="item"><img src="/assets/norway.jpg"></div>
		<div class="item"><img src="/assets/orca.jpg"></div>
		<div class="item"><img src="/assets/redpanda.jpg"></div>
		<div class="item"><img src="/assets/rhino.jpg"></div>
		<div class="item"><img src="/assets/suncave.jpg"></div>
		<div class="item"><img src="/assets/sunrise.jpg"></div>
		<div class="item"><img src="/assets/tetonrange.jpg"></div>
	</div>

</div>

<script src="jquery-1.7.1.min.js"></script>
<script src="jquery.masonry.min.js"></script>
<script src="http://cdnjs.cloudflare.com/ajax/libs/masonry/3.3.0/masonry.pkgd.js"></script>
<script src="http://imagesloaded.desandro.com/imagesloaded.pkgd.js"></script>
<script>
$(document).ready(function() {
	var container = document.querySelector('#container');
	var msnry;
	// initialize Masonry after all images have loaded
	imagesLoaded( container, function() {
	  msnry = new Masonry( container );
	});

});
</script>

app/views/posts/new.html.erb
<%= render 'form' %>

app/views/posts/show.html.erb
<h1>Posts#show</h1>
<p>Find me in app/views/posts/show.html.erb</p>

app/views/vibes/_form.html.erb
<div class="mainForm">
	<%= form_for(@vibe) do |f| %>

	Type: <%= f.select :vibeType, [['image', 1], ['soundcloud', 2], ['youtube', 3]] %>
		Title: <%= f.text_field :title %>
		Body: <%= f.text_field :body %>
		URL: <%= f.text_field :url %>

		<%= f.submit "submit" %>

	<% end %>
</div>

app/views/vibes/edit.html.erb
<%= render 'form' %>

app/views/vibes/index.html.erb
<div class="mainForm">
<h1 id="header-button"><%= link_to "submit", new_vibe_path %> </h1>

	<div id="container" data-masonry-options='{ "itemSelector": ".item", "columnWidth": 320 }'>
	
		<% @vibe.each do |vibe| %>
			<% if vibe.vibeType == "2" %>
				<div class="item"> 
					<iframe width="300" scrolling="no" frameborder="no" src="<%= vibe.getSrc.to_s %>" ></iframe> 
				</div>
			<% elsif vibe.vibeType == "3" %>
				<div class="item"> 
					<iframe width="300" height="250" frameborder="0"src="<%= vibe.getSrc.to_s %>" allowfullscreen> </iframe> 
				</div>
			<% end %>
		<% end %>
		<div class="item"><img src="/assets/rolf.jpg"></div>
		<div class="item"><img src="/assets/braislakeitaly.jpg"></div>
		<div class="item"><img src="/assets/chilevolcano.jpg"></div>
		<div class="item"><img src="/assets/coolhaus.jpg"></div>
		<div class="item"><iframe src="https://www.youtube.com/embed/lCDKk2s0pQM" frameborder="0" allowfullscreen></iframe></div>
		<div class="item"><img src="/assets/fireflies.jpg"></div>
		<div class="item"><img src="/assets/nice.jpg"></div>
		<div class="item"><iframe scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/202830372&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false&amp;visual=true"></iframe></div>
		<div class="item"><img src="/assets/norway.jpg"></div>
		<div class="item"><img src="/assets/orca.jpg"></div>
		<div class="item"><img src="/assets/redpanda.jpg"></div>
		<div class="item"><img src="/assets/rhino.jpg"></div>
		<div class="item"><img src="/assets/suncave.jpg"></div>
		<div class="item"><img src="/assets/sunrise.jpg"></div>
		<div class="item"><img src="/assets/tetonrange.jpg"></div>
	</div>
</div>

<script src="jquery-1.7.1.min.js"></script>
<script src="jquery.masonry.min.js"></script>
<script src="http://cdnjs.cloudflare.com/ajax/libs/masonry/3.3.0/masonry.pkgd.js"></script>
<script src="http://imagesloaded.desandro.com/imagesloaded.pkgd.js"></script>
<script>
$(document).ready(function() {
	var container = document.querySelector('#container');
	var msnry;
	// initialize Masonry after all images have loaded
	imagesLoaded( container, function() {
	  msnry = new Masonry( container );
	});

});
</script>

app/views/vibes/new.html.erb
<%= render 'form' %>

app/views/vibes/show.html.erb
<h1>Vibes#show</h1>
<p>Find me in app/views/vibes/show.html.erb</p>